name: bump
on:
  workflow_dispatch:

jobs:
  bump:
    name: increase version numbers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: create local release branch
        run: git fetch origin release/arrowsquid:release/arrowsquid

      - name: check change files
        run: node common/scripts/install-run-rush.js change --verify --target-branch origin/release/arrowsquid

      - name: bump versions
        run: node common/scripts/install-run-rush.js version --bump --target-branch release/arrowsquid

      - name: merge back release branch
        run: |
          git checkout "${GITHUB_REF##*/}"
          git fetch origin release/arrowsquid
          git merge release/arrowsquid
          git push origin "${GITHUB_REF##*/}"
