name: tag ArrowSquid
on:
  workflow_dispatch:

jobs:
  test:
    name: Tag ArrowSquid npm packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Write npm credentials
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc-publish
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Set tags
        run: ops/npm-tag-arrowsquid.sh

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1
#        with:
#          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
#          limit-access-to-actor: true
#          ## limits ssh access and adds the ssh public keys of the listed GitHub users
#          limit-access-to-users: eldargab
